<?php

function alma_calendar_theme($existing, $type, $theme, $path)
{
    return array(
        'all_hours_display' => array(
            'variables' => array(
                'orbach' => null,
                'scua' => null,
                'rivera' => null,
                'music' => null,
            ),
            'template' => 'all-hours',
        ),

        'today_hours_display' => array(
            'variables' => array(
                'is_open' => null,
                'hours' => null,
            ),
            'template' => 'today-hours',
        ),

        'homepage_hours_display' => array(
            'template' => 'homepage-hours'
        )
    );
}
