<?php

function eventbrite_theme($existing, $type, $theme, $path) {
    return array(
        'events_list_display' => array(
            'variables' => array(
                'events' => NULL
            ),
            'template' => 'events-list',
        ),
        'events_carousel_display' => array(
            'variables' => array(
                'events' => NULL
            ),
            'template' => 'events-carousel',
        ),
    );
}