<?php

/**
 * @file
 * Contains landing page functionality for Lightning.
 */

use Drupal\field\FieldConfigInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityDescriptionInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_library_info_alter().
 */
function ucr_core_library_info_alter(array &$libraries, $extension) {
  if ($extension == 'seven') { // Add this only to the seven theme.
    $url = drupal_get_path('module', 'ucr_core') . '/css/components/icons.min.css';
    $url = file_create_url($url);
    $url = file_url_transform_relative($url);

    $libraries['global-styling']['css']['component'][$url] = [];

    $url = drupal_get_path('module', 'ucr_core') . '/css/components/media-browser.css';
    $url = file_create_url($url);
    $url = file_url_transform_relative($url);

    $libraries['global-styling']['css']['component'][$url] = [];
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ucr_core_field_config_insert(FieldConfigInterface $field) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
}

/**
 * Implements hook_modules_installed().
 */
function ucr_core_modules_installed(array $modules) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
}

function ucr_core_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('node_page_form', 'node_page_edit_form'))) {
    $form['keywords'] = [
      '#type' => 'details',
      '#title' => t('Content Keywords'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 100,
      '#optional' => true,
      '#open' => true,
    ];

    $form['field_content_keywords']['#group'] = 'keywords';
  }

  return $form;
}

/**
 * Implements hook_layout_alter().
 */
function ucr_core_layout_alter(&$definitions) {
  // Disable default layouts.
  //unset($definitions['layout_onecol']);
  unset($definitions['layout_twocol']);
  unset($definitions['layout_twocol_bricks']);
  unset($definitions['layout_threecol_25_50_25']);
  unset($definitions['layout_threecol_33_34_33']);
}

function ucr_core_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      $original_formats = $settings['editor']['formats'][$text_format_id]['editorSettings']['format_tags'];
      $removed_h1_tag = preg_replace('/h1;/', '', $original_formats);
      $settings['editor']['formats'][$text_format_id]['editorSettings']['format_tags'] = $removed_h1_tag.";address;div";
    }
  }
}