<?php

/**
 * @file
 * Module file for ucr_global.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_alter().
 */
function ucr_global_block_view_alter(array &$build, BlockPluginInterface $block) {
  $config = \Drupal::config('ucr_global.settings');
  $text = $config->get('audience_links_text');
  // We'll search for the string 'Audience links'.
  $definition = $block->getPluginDefinition();
  if ((!empty($build['#configuration']['label']) && stristr($build['#configuration']['label'], 'audience links')) || (!empty($definition['subject']) && stristr($definition['subject'], 'audience links'))) {
    // This will uppercase the block title.
    $build['#configuration']['label'] = $text;
  }
}
